### ISSUE TITLE
LiteralList generates a bad SPARQL value

### ISSUE THREAD

**Issue by pchampin** [sparna-git/Sparnatural#389] opened 2022-11-25 11:38 UTC
I'm using the following configuration snippet
```turtle
spoty:macroarea a owl:DatatypeProperty;
  rdfs:subPropertyOf config-core:LiteralListProperty ;
  config-datasources:datasource this:literal_list_alpha_with_count;
  rdfs:label "utilisé dans"@fr, "used in"@en;
  rdfs:domain spoty:Language;
  rdfs:range this:Macroarea;
  config-core:isMultilingual true;
.
this:Macroarea a owl:Class ;
    rdfs:subClassOf rdfs:Literal ;
    config-core:faIcon "fa-duotone fa-earth-europe";
    config-core:order 90;
    rdfs:label "Macroarea"@fr, "Macroarea"@en;
.
```
When I select one value, the generated SPARQL query is invalid:
```sparql
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT DISTINCT ?this ?this_label WHERE {
  ?this rdf:type <https://aslan.universite-lyon.fr/spoty/ns/Language>.
  ?this <https://aslan.universite-lyon.fr/spoty/ns/macroarea> <Eurasia>.
  ?this rdfs:label ?this_label.
  FILTER(LANGMATCHES(LANG(?this_label), "fr"))
}
LIMIT 1000
```
(see `<Eurasia>` instead of `"Eurasia"` in line 5

Interestingly, if I ask to see the 'Macroarea' variable, or if I select several values, the SPARQL query contains a VALUES statement that is correctly uses literals:
```sparql
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT DISTINCT ?this ?this_label ?Macroarea_1 WHERE {
  ?this rdf:type <https://aslan.universite-lyon.fr/spoty/ns/Language>.
  ?this <https://aslan.universite-lyon.fr/spoty/ns/macroarea> ?Macroarea_1.
  VALUES ?Macroarea_1 {
    "Eurasia"
  }
  ?this rdfs:label ?this_label.
  FILTER(LANGMATCHES(LANG(?this_label), "fr"))
}
LIMIT 1000
```

**Comment by tfrancart** [comment] 2022-11-25 12:58
Hello @pchampin ! Thanks for the feedback. Before looking into it in details, 2 general comments:

- We are in the process of transitioning to a new major versio in Typescript, currently on branch "issue-298-TS", also known as "V8". The current javascript version can accept bugfixes only. You might to try with the new version if the issue is solved there.
- this Literal list feature is not widely used and was known to be buggy (see e.g. https://github.com/sparna-git/Sparnatural/issues/343)
- Can you confirm if you tried with the latest release, or with the current master branch ? you could also try with the current master branch (which would require you to compile the beast)

**Comment by tfrancart** [comment] 2022-12-14 16:04
You might have a problem in your config : you used `this:literal_list_alpha_with_count`, with the `this` namespace indicating it is a datasource that you have defined yourself; but I suspect you wanted to reference an existing datasource, in that case `config-datasources:literal_list_alpha_with_count`.

In the newest Typescript version, the LiteralListWidget is working, see an example at https://sparnatural.eu/demos/demo-dbpedia-v2/, with Person > publisher > Texte ("éditeurs").

I let you close the issue if it is OK for you

**Closed** 2023-04-19 19:47 UTC
